[build]
builder = "dockerfile"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "n8n"

[services.variables]
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "${{ RAILWAY_PUBLIC_DOMAIN ? 'https' : 'http' }}"
WEBHOOK_URL = "${{ RAILWAY_PUBLIC_DOMAIN ? 'https://' + RAILWAY_PUBLIC_DOMAIN : 'http://localhost:5678' }}"
GENERIC_TIMEZONE = "America/New_York"
N8N_METRICS = "true"