[build]
builder = "dockerfile"

[deploy]
startCommand = "n8n start"
healthcheckPath = "/healthz"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
N8N_HOST = "0.0.0.0"
N8N_PORT = "5678"
N8N_PROTOCOL = "http"
GENERIC_TIMEZONE = "America/New_York"
N8N_METRICS = "true"
N8N_LOG_LEVEL = "info"
N8N_DISABLE_UI = "false"